// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omilhfohvstqsonhyuxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taWxoZm9odnN0cXNvbmh5dXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODIwNDcsImV4cCI6MjA4NDc1ODA0N30.q-eehykU4N_lfKiYvjgn_QepEGu_6aRQpQSl1myIvCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});